abrir EXCEL, baixa planilha txt, E CONVERTER COLUNAS USANDO "|", DEIXANDO UMA LINHA ACIMA LIVRE, PARA NUMERAR AS COLUNAS: 1 ATE 38. FEITO ISTO SALVA, E FECHA O EXCEL, LOGO APOS SALVA NO DRIVER (VERIFICAR A PASTA), E SIGA PASSOS ABAIXO.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
path= "/content/drive/MyDrive/ADRIANOSET23/ARQmODELO_EXCEL_FILTRO02nov23.xlsx" ##COLOCAR NOME ARQUIVO AQUI

In [3]:
df = pd.read_excel(path)

In [4]:
df = df[[int(i) for i in [1,3,5,8,12 ]]] ##[1,3,  5,8 , 12 ]]]

In [5]:
df = df[df[1].isin(['C100', 'C190', 'C590','D190'])]
df

        1     3          5      8          12
136   C100     0         55  17998  134667.87
140   C190  1102  134667.87      0        NaN
141   C100     0         55  17999   26754.88
146   C190  1102   26754.88      0        NaN
147   C100     0         55  18000   24042.85
...    ...   ...        ...    ...        ...
3690  D190  2353       9920      0        NaN
3692  D190  2353    9564.16      0        NaN
3694  D190  2353    11662.2      0        NaN
3696  D190  2353       8904      0        NaN
3699  D190  2353     6618.5      0        NaN

[1306 rows x 5 columns]

In [ ]:
# df.to_excel(f"/content/drive/MyDrive/ADRIANOSET23/filtrovaldir.xlsx")##MUDAR NOME ARQ GERADO

In [6]:
print(df)

        1     3          5      8          12
136   C100     0         55  17998  134667.87
140   C190  1102  134667.87      0        NaN
141   C100     0         55  17999   26754.88
146   C190  1102   26754.88      0        NaN
147   C100     0         55  18000   24042.85
...    ...   ...        ...    ...        ...
3690  D190  2353       9920      0        NaN
3692  D190  2353    9564.16      0        NaN
3694  D190  2353    11662.2      0        NaN
3696  D190  2353       8904      0        NaN
3699  D190  2353     6618.5      0        NaN

[1306 rows x 5 columns]

ABAIXO tirar o '#' e  COLOCAR NOME ARQUIVO, e clicar. pronto o arq foi gerado no drive.

In [ ]:
# df.to_excel(f'/content/drive/MyDrive/ADRIANOSET23/zzzzNOMEARQ.xlsx')